# Generated by Django 4.2.7 on 2023-12-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('ename', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('sal', models.PositiveIntegerField()),
                ('comm', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=100)),
                ('deptno', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('grade', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('low_sal', models.PositiveIntegerField()),
                ('high_sal', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('ename', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('eid', models.PositiveIntegerField()),
                ('sal', models.PositiveIntegerField()),
                ('deptno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
